language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t pauloes/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true pauloes/docker-react npm run test
# script:
#   - docker run USERNAME/docker-react npm run test -- --coverage

# instead should be:

# script:
#
