sudo: require
language: generic

services:
  - docker

before_install:
  - docker build -t pauloes/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true pauloes/docker-react yarn test -- --coverage
